# Generated by Django 2.2.12 on 2023-11-24 18:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='summary',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
