# Generated by Django 2.2.12 on 2023-11-24 19:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0002_player_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='long',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
