# Generated by Django 2.2.12 on 2023-11-24 19:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0003_player_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='long',
        ),
        migrations.AlterField(
            model_name='player',
            name='summary',
            field=otree.db.models.LongStringField(max_length=1000, null=True),
        ),
    ]
