# Generated by Django 2.2.12 on 2023-11-24 20:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0004_auto_20231124_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='summary',
            field=otree.db.models.LongStringField(max_length=1200, null=True),
        ),
    ]
