# Generated by Django 2.2.12 on 2023-11-24 20:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0008_remove_player_game_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='summary',
            field=otree.db.models.LongStringField(max_length=2000, null=True),
        ),
    ]
