# Generated by Django 2.2.12 on 2023-11-24 20:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0009_auto_20231124_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='familiar',
            field=otree.db.models.IntegerField(blank=True, choices=[[True, 'It did'], [False, 'It did not']], null=True),
        ),
    ]
