# Generated by Django 2.2.12 on 2023-11-24 20:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0011_auto_20231124_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='familiar',
            field=otree.db.models.IntegerField(choices=[[1, 'Low'], [2, 'Medium'], [3, 'High']], null=True),
        ),
    ]
