# Generated by Django 2.2.12 on 2023-11-24 20:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0021_auto_20231124_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='familiar',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [2, 'No'], [3, 'Not Sure']], null=True, verbose_name='Had you known this project before?'),
        ),
    ]
