# Generated by Django 2.2.12 on 2023-11-24 21:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0022_auto_20231124_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cameras',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='clarity',
            field=otree.db.models.IntegerField(choices=[[1, '1 (Not clear at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Completely clear)']], null=True, verbose_name='Would you like to learn more about the project?'),
        ),
        migrations.AddField(
            model_name='player',
            name='connection',
            field=otree.db.models.IntegerField(choices=[[1, '1 (Not at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Very well)']], null=True, verbose_name='Do you think the speaker could connect well with the audience?'),
        ),
        migrations.AddField(
            model_name='player',
            name='easiness',
            field=otree.db.models.IntegerField(choices=[[1, '1 (way too easy?)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (way too difficult?)']], null=True, verbose_name='For you, was the presentation...'),
        ),
        migrations.AddField(
            model_name='player',
            name='enjoy',
            field=otree.db.models.IntegerField(choices=[[1, '1 (Not at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Very much)']], null=True, verbose_name='How much did you enjoy the presentation?'),
        ),
        migrations.AddField(
            model_name='player',
            name='remarks',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='knowledge',
            field=otree.db.models.IntegerField(choices=[[1, '1 (No prior knowledge)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Expert prior knowledge)']], null=True, verbose_name='How would you assess your knowledge of the topic, prior to the talk?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='like',
            field=otree.db.models.IntegerField(choices=[[1, '1 (I certainly would not)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (I certainly would)']], null=True, verbose_name='Would you like to learn more about the project?'),
        ),
    ]
