# Generated by Django 2.2.12 on 2023-11-24 21:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0024_auto_20231124_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='remarks',
            field=otree.db.models.LongStringField(null=True, verbose_name='Any further remarks, reflections on your experience as a Listener or specific suggestions for the Speaker?'),
        ),
    ]
