# Generated by Django 2.2.12 on 2023-11-24 21:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0026_auto_20231124_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guess',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
