# Generated by Django 2.2.12 on 2023-11-24 22:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0054_auto_20231124_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cameras_good',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name=''),
        ),
    ]
