# Generated by Django 2.2.12 on 2023-11-24 22:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0067_auto_20231124_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='FEEDBACK',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTION9',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='allowance_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='allowance_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assumed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assumed_one',
        ),
        migrations.RemoveField(
            model_name='player',
            name='commissioner_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='commissioner_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='emails_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='emails_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='germans_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='germans_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='laptops_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='laptops_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='paper_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='paper_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='printers_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='printers_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skip_all',
        ),
        migrations.RemoveField(
            model_name='player',
            name='temporary_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='temporary_lower',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tickets_higher',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tickets_lower',
        ),
        migrations.AddField(
            model_name='player',
            name='TREATMENT',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='guess1_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF)'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess2',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON)'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess2_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF)'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess3',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON)'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess3_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF)'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess4',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON)'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess4_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF)'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess5',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON)'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='guess5_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF)'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess1',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON)'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
    ]
