# Generated by Django 2.2.12 on 2023-11-24 22:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0068_auto_20231124_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guess1',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess1_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess2',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess2_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess3',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess3_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess4',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess4_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess5',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are ON'], [2, '5-15% higher when cameras are ON'], [3, 'about the same'], [4, '5-15% higher when cameras are OFF'], [5, 'more than 15% higher when cameras are OFF']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='guess5_reversed',
            field=otree.db.models.IntegerField(choices=[[1, 'more than 15% higher when cameras are OFF'], [2, '5-15% higher when cameras are OFF'], [3, 'about the same'], [4, '5-15% higher when cameras are ON'], [5, 'more than 15% higher when cameras are ON']], null=True, verbose_name=''),
        ),
    ]
