# Generated by Django 2.2.12 on 2023-12-01 10:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0070_auto_20231201_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='summary',
            field=otree.db.models.LongStringField(max_length=3000, null=True, verbose_name=''),
        ),
    ]
