# Generated by Django 2.2.12 on 2023-12-01 10:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_listeners', '0071_auto_20231201_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='summary',
            field=otree.db.models.LongStringField(null=True, verbose_name=''),
        ),
    ]
