# Generated by Django 2.2.12 on 2023-11-25 09:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cameras_off',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cameras_on',
        ),
        migrations.RemoveField(
            model_name='player',
            name='familiar',
        ),
        migrations.RemoveField(
            model_name='player',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='player',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='player',
            name='summary',
        ),
        migrations.AddField(
            model_name='player',
            name='asses1',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='asses2',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='asses3',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='asses4',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='asses5',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='asses6',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='asses7',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess1_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess2_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess3_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess4_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess5_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess6_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess7_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment WILL be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='cameras',
            field=otree.db.models.LongStringField(null=True, verbose_name='As you have noticed, cameras were on during one of your talks and off during the other talk. How do you think this affected your performance and everyone’s experience?'),
        ),
        migrations.AddField(
            model_name='player',
            name='fake',
            field=otree.db.models.IntegerField(choices=[[1, 'Summary 1'], [2, 'Summary 2'], [3, 'Summary 3'], [4, 'Summary 4'], [5, 'Summary 5'], [6, 'Summary 6'], [7, 'Summary 7']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='rec_kept',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes, I am OK with it'], [2, 'No, I want the recording to be deleted'], [3, 'I don’t know yet, please send me the recording before I decide']], null=True, verbose_name='<p><font color="#33CC33">Do you agree that the recording of your talk is kept, possibly to be shared within the Commission to promote your project? </font>It also means taking part in the competition for the best talk. If you give consent after each of your two performances, they will have an independent chance in the competition.</p> <p> Please note that if you choose “Yes”, we will also send you the recording).</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='reflections',
            field=otree.db.models.LongStringField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='satisfied',
            field=otree.db.models.IntegerField(choices=[[1, '1 (Not at all satisfied)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Fully satisfied)']], null=True, verbose_name='How satisfied are you with your talk?'),
        ),
        migrations.AddField(
            model_name='player',
            name='sure',
            field=otree.db.models.IntegerField(choices=[[0, '0 (It’s a random guess)'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (I am 100% sure)']], null=True, verbose_name='How sure are you of your answer?'),
        ),
    ]
