# Generated by Django 2.2.12 on 2023-11-25 09:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0005_auto_20231125_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='asses1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asses2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asses3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asses4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asses5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asses6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asses7',
        ),
        migrations.AddField(
            model_name='player',
            name='assess1',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess2',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess3',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess4',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess5',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess6',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
        migrations.AddField(
            model_name='player',
            name='assess7',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='<p style="line-height:1.7;font-size:19px">On a scale of 0 to 7, how would you assess this summary? Please note that this assessment WILL NOT be sent to the relevant Listener.</p>'),
        ),
    ]
