# Generated by Django 2.2.12 on 2023-11-25 09:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0008_auto_20231125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assess2',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='On a scale of 0 to 7, how would you assess this summary? Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess3',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='On a scale of 0 to 7, how would you assess this summary? Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess4',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='On a scale of 0 to 7, how would you assess this summary? Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess5',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='On a scale of 0 to 7, how would you assess this summary? Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess6',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='On a scale of 0 to 7, how would you assess this summary? Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess7',
            field=otree.db.models.IntegerField(choices=[[1, '1 (This text does not summarise my project at all)'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (This text is an excellent summary of my project)']], null=True, verbose_name='On a scale of 0 to 7, how would you assess this summary? Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
    ]
