# Generated by Django 2.2.12 on 2023-12-01 08:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0011_auto_20231201_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assess1_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='<p style="line-height:1.7;font-size:19px">What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.</p>'),
        ),
    ]
