# Generated by Django 2.2.12 on 2023-12-01 21:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0012_auto_20231201_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fake',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sure',
        ),
        migrations.AddField(
            model_name='player',
            name='gpt',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gpt2',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gpt3',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gpt4',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gpt5',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gpt6',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gpt7',
            field=otree.db.models.IntegerField(choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='clarity',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Not clear at all) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Completely clear)']], null=True, verbose_name='How clear was your presentation?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='connection',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Not at all) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Very well)']], null=True, verbose_name='Did they think you could connect well with the audience?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='easiness',
            field=otree.db.models.IntegerField(blank=True, choices=[[-3, '(way too difficult?) -3'], [-2, '-2'], [-1, '-1'], [0, '0'], [1, '1'], [2, '2'], [3, '3 (way too easy?)']], null=True, verbose_name='For them, was your presentation...'),
        ),
        migrations.AlterField(
            model_name='player',
            name='enjoy',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Not at all) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Very much)']], null=True, verbose_name='How much did they enjoy your presentation?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='like',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(They certainly would not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (They certainly would)']], null=True, verbose_name='Would they like to learn more about your project?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='reflections',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name=''),
        ),
    ]
