# Generated by Django 2.2.12 on 2023-12-01 21:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0014_auto_20231201_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assess2_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess3_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess4_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess5_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess6_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess7_txt',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='What aspects of this summary do you particularly like or dislike? Any other thoughts about it? Please note that this assessment <b>WILL</b> be sent to the relevant Listener.'),
        ),
    ]
