# Generated by Django 2.2.12 on 2023-12-01 21:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0015_auto_20231201_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gpt',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpt2',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpt3',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpt4',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpt5',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpt6',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gpt7',
            field=otree.db.models.IntegerField(blank=True, choices=[[0, '(Definitely not) 0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7 (Definitely yes)']], null=True, verbose_name='Do you think this summary was written by Chat GPT?'),
        ),
    ]
