# Generated by Django 2.2.12 on 2023-12-01 21:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras_speakers', '0019_auto_20231201_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assess2',
            field=otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How would you assess this summary? Please choose on a <b>scale from 0</b> ("This text does not summarise my project at all") <b>to 7</b> ("This text is an excellent summary ofmy project").Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess3',
            field=otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How would you assess this summary? Please choose on a <b>scale from 0</b> ("This text does not summarise my project at all") <b>to 7</b> ("This text is an excellent summary ofmy project").Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess4',
            field=otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How would you assess this summary? Please choose on a <b>scale from 0</b> ("This text does not summarise my project at all") <b>to 7</b> ("This text is an excellent summary ofmy project").Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess5',
            field=otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How would you assess this summary? Please choose on a <b>scale from 0</b> ("This text does not summarise my project at all") <b>to 7</b> ("This text is an excellent summary ofmy project").Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess6',
            field=otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How would you assess this summary? Please choose on a <b>scale from 0</b> ("This text does not summarise my project at all") <b>to 7</b> ("This text is an excellent summary ofmy project").Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assess7',
            field=otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7']], null=True, verbose_name='How would you assess this summary? Please choose on a <b>scale from 0</b> ("This text does not summarise my project at all") <b>to 7</b> ("This text is an excellent summary ofmy project").Please note that this assessment <b>WILL NOT</b> be sent to the relevant Listener.'),
        ),
    ]
