# Generated by Django 2.2.12 on 2023-09-20 15:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals_group', to='otree.Session')),
            ],
            options={
                'db_table': 'intervals_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'intervals_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_is_waiting', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('feedback', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('no_feedback', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('final', otree.db.models.LongStringField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">It is typically found in such studies that<b> much less than 90% of the intervals cover the actual number</b>. Of course, in some cases it can be bad luck, but given that this happens systematically, it is interpreted as what scholars call “overprecision”: many people tend to <b>overestimate the precision of their judgment</b>. This tendency has important consequences for the quality of decision-making in many domains. For example, it might make you underdiversify your investment portfolio ("put all your eggs in the same basket"). <b>If you are managing a project, you may underestimate the likelihood that it ends up taking much more time and money than expected</b>. See e.g., <a href="https://www.researchgate.net/profile/Elizabeth-Tenney/publication/316228342_Overprecision_in_Judgment/links/60abfb7b299bf1031fc843a8/Overprecision-in-Judgment.pdf" target="_blank">Overprecision in Judgment (Moore et al.)</a> to learn more (in particular, see section <em>Ecological Evidence of Overprecision</em> for some examples of real-life consequences of overprecision). For example, you will learn about the advantages and limitations of the kind of study you have just participated in.</span><span></span><span style="line-height:1.7;font-size:18px">Interestingly, many people guess that less than 90% of their intervals will cover the true values, probably intuiting their own overprecision.</span><p></p><span style="line-height:1.7;font-size:18px">If you have any (further) comments on the experiment, please make them below, ideally signing them. You can also contact me directly (e.g.if you want to provide your comments in a conversation -- that would be most helpful).</span><right> <span style="line-height:1.7;font-size:18px">Michal Krawczyk</span></right>')),
                ('germans_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">The European Commission has about 32,000 employees. How many of them are German native speakers?</span><span style="line-height:1.7;font-size:18px"><font color =\'green\'>Please answer in <b>absolute numbers</b>, not in terms of percentage of the total number of employees.</font></span><span style="line-height:1.7;font-size:18px"><p></p> I am 90% sure that the number is between</span>')),
                ('germans_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span otree>and</span>')),
                ('temporary_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">The European Commission has about 32,000 employees. How many of them are temporary staff? </span><span style="line-height:1.7;font-size:18px"><font color =\'green\'>Please answer in <b>absolute numbers</b>, not in terms of percentage of the total number of employees. </font></span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('temporary_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('commissioner_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">How many<b> different </b>people ever served as European Commissioners (it counts as one if the same individual was a member of two or more Commissions)?</span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('commissioner_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('age_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">What is she average age of the 27 members of the von der Leyen Commission?</span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('age_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('allowance_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">What was, back in 2016, the monthly “entertainment allowance” of the President of the Commission (in EUR)?</span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('allowance_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('paper_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">The EC used about 300 tonnes of office paper in 2020. How many tonnes did it use in 2019? </span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('paper_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('printers_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">The EC had about 7360 individual printers in 2018. How many did it have in 2019? </span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('printers_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('emails_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">How many e-mails does a typical EC employee send (from his or her corporate account) on a typical working day? </span><span style="line-height:1.7;font-size:18px"><p></p> I am 90% sure that the <b>number</b> is between</span>')),
                ('emails_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('laptops_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">How many laptops does the EC purchase yearly?</span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('laptops_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('tickets_lower', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">What is the average <b>daily</b> number of tickets (requests) that the IT helpdesk of the EC receives?</span><span style="line-height:1.7;font-size:18px"> <p></p> I am 90% sure that the number is between</span>')),
                ('tickets_higher', otree.db.models.IntegerField(blank=True, null=True, verbose_name='<span style="line-height:1.7;font-size:18px">and</span>')),
                ('skip_all', otree.db.models.BooleanField(blank=True, choices=[[True, 'Yes, next question, please!'], [False, 'No more questions, please, just tell me what it’s about!']], default=True, null=True, verbose_name='<p></p><span style="line-height:1.7;font-size:30px"></span>Do you want to continue?')),
                ('assumed', otree.db.models.IntegerField(null=True, verbose_name='')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intervals.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervals.Subsession')),
            ],
            options={
                'db_table': 'intervals_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervals.Subsession'),
        ),
    ]
