# Generated by Django 2.2.12 on 2023-09-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0004_auto_20230920_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='player',
            name='no_feedback',
        ),
    ]
