# Generated by Django 2.2.12 on 2023-09-30 11:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0006_player_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='feedback',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='<span style="line-height:0.1;font-size:0.1px">and</span>'),
        ),
    ]
