# Generated by Django 2.2.12 on 2023-09-30 12:31

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0009_player_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='player',
            name='no_feedback',
        ),
        migrations.RemoveField(
            model_name='player',
            name='treatment',
        ),
        migrations.AddField(
            model_name='player',
            name='FEEDBACK',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
