# Generated by Django 2.2.12 on 2023-10-06 20:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0011_auto_20231006_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='QUESTIONS9',
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION10',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION2',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION3',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION4',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION5',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION6',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION7',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION8',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='QUESTION9',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
