# Generated by Django 2.2.12 on 2023-10-07 07:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0012_auto_20231006_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assumed_one',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
