# Generated by Django 2.2.12 on 2023-10-07 08:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0013_player_assumed_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assumed_one',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name=''),
        ),
    ]
