# Generated by Django 2.2.12 on 2023-10-09 06:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0016_auto_20231008_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assumed',
            field=otree.db.models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='assumed_one',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name=''),
        ),
    ]
