# Generated by Django 2.2.12 on 2023-10-13 11:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0017_auto_20231009_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assumed_one',
            field=otree.db.models.BooleanField(blank=True, choices=[[False, 'It did not'], [True, 'It did']], null=True),
        ),
    ]
