# Generated by Django 2.2.12 on 2022-12-17 13:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods_ibex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contribution_2',
            field=otree.db.models.CurrencyField(null=True, verbose_name='How much will you contribute?'),
        ),
        migrations.AddField(
            model_name='player',
            name='contribution_3',
            field=otree.db.models.CurrencyField(null=True, verbose_name='How much will you contribute?'),
        ),
    ]
