# Generated by Django 2.2.12 on 2023-06-17 08:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods_ibex', '0003_auto_20221217_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='feeling',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
