# Generated by Django 2.2.12 on 2023-06-17 08:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods_ibex', '0004_group_feeling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='feeling',
        ),
        migrations.AddField(
            model_name='player',
            name='feeling',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
